services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sakila-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: sakila123
    ports:
      - "3306:3306"
    volumes:
      - ./sakila-mysql.sql:/docker-entrypoint-initdb.d/sakila-mysql.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
